# CMake generated Testfile for 
# Source directory: D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING
# Build directory: D:/persiansph/Persiansph/persiansph/persiansph/LapackBuild/BLAS/TESTING
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(BLAS-xblat1s "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=D:/persiansph/Persiansph/persiansph/persiansph/LapackBuild/bin/xblat1s.exe" "-DINTDIR=." "-P" "D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/TESTING/runtest.cmake")
set_tests_properties(BLAS-xblat1s PROPERTIES  _BACKTRACE_TRIPLES "D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;42;add_test;D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;50;add_blas_test;D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;0;")
add_test(BLAS-xblat2s "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=D:/persiansph/Persiansph/persiansph/persiansph/LapackBuild/bin/xblat2s.exe" "-DINPUT=D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/sblat2.in" "-DINTDIR=." "-P" "D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/TESTING/runtest.cmake")
set_tests_properties(BLAS-xblat2s PROPERTIES  _BACKTRACE_TRIPLES "D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;36;add_test;D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;51;add_blas_test;D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;0;")
add_test(BLAS-xblat3s "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=D:/persiansph/Persiansph/persiansph/persiansph/LapackBuild/bin/xblat3s.exe" "-DINPUT=D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/sblat3.in" "-DINTDIR=." "-P" "D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/TESTING/runtest.cmake")
set_tests_properties(BLAS-xblat3s PROPERTIES  _BACKTRACE_TRIPLES "D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;36;add_test;D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;52;add_blas_test;D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;0;")
add_test(BLAS-xblat1d "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=D:/persiansph/Persiansph/persiansph/persiansph/LapackBuild/bin/xblat1d.exe" "-DINTDIR=." "-P" "D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/TESTING/runtest.cmake")
set_tests_properties(BLAS-xblat1d PROPERTIES  _BACKTRACE_TRIPLES "D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;42;add_test;D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;56;add_blas_test;D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;0;")
add_test(BLAS-xblat2d "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=D:/persiansph/Persiansph/persiansph/persiansph/LapackBuild/bin/xblat2d.exe" "-DINPUT=D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/dblat2.in" "-DINTDIR=." "-P" "D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/TESTING/runtest.cmake")
set_tests_properties(BLAS-xblat2d PROPERTIES  _BACKTRACE_TRIPLES "D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;36;add_test;D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;57;add_blas_test;D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;0;")
add_test(BLAS-xblat3d "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=D:/persiansph/Persiansph/persiansph/persiansph/LapackBuild/bin/xblat3d.exe" "-DINPUT=D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/dblat3.in" "-DINTDIR=." "-P" "D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/TESTING/runtest.cmake")
set_tests_properties(BLAS-xblat3d PROPERTIES  _BACKTRACE_TRIPLES "D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;36;add_test;D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;58;add_blas_test;D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;0;")
add_test(BLAS-xblat1c "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=D:/persiansph/Persiansph/persiansph/persiansph/LapackBuild/bin/xblat1c.exe" "-DINTDIR=." "-P" "D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/TESTING/runtest.cmake")
set_tests_properties(BLAS-xblat1c PROPERTIES  _BACKTRACE_TRIPLES "D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;42;add_test;D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;62;add_blas_test;D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;0;")
add_test(BLAS-xblat2c "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=D:/persiansph/Persiansph/persiansph/persiansph/LapackBuild/bin/xblat2c.exe" "-DINPUT=D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/cblat2.in" "-DINTDIR=." "-P" "D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/TESTING/runtest.cmake")
set_tests_properties(BLAS-xblat2c PROPERTIES  _BACKTRACE_TRIPLES "D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;36;add_test;D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;63;add_blas_test;D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;0;")
add_test(BLAS-xblat3c "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=D:/persiansph/Persiansph/persiansph/persiansph/LapackBuild/bin/xblat3c.exe" "-DINPUT=D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/cblat3.in" "-DINTDIR=." "-P" "D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/TESTING/runtest.cmake")
set_tests_properties(BLAS-xblat3c PROPERTIES  _BACKTRACE_TRIPLES "D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;36;add_test;D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;64;add_blas_test;D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;0;")
add_test(BLAS-xblat1z "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=D:/persiansph/Persiansph/persiansph/persiansph/LapackBuild/bin/xblat1z.exe" "-DINTDIR=." "-P" "D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/TESTING/runtest.cmake")
set_tests_properties(BLAS-xblat1z PROPERTIES  _BACKTRACE_TRIPLES "D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;42;add_test;D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;68;add_blas_test;D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;0;")
add_test(BLAS-xblat2z "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=D:/persiansph/Persiansph/persiansph/persiansph/LapackBuild/bin/xblat2z.exe" "-DINPUT=D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/zblat2.in" "-DINTDIR=." "-P" "D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/TESTING/runtest.cmake")
set_tests_properties(BLAS-xblat2z PROPERTIES  _BACKTRACE_TRIPLES "D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;36;add_test;D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;69;add_blas_test;D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;0;")
add_test(BLAS-xblat3z "C:/Program Files/CMake/bin/cmake.exe" "-DTEST=D:/persiansph/Persiansph/persiansph/persiansph/LapackBuild/bin/xblat3z.exe" "-DINPUT=D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/zblat3.in" "-DINTDIR=." "-P" "D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/TESTING/runtest.cmake")
set_tests_properties(BLAS-xblat3z PROPERTIES  _BACKTRACE_TRIPLES "D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;36;add_test;D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;70;add_blas_test;D:/persiansph/Persiansph/persiansph/persiansph/lapack-3.5.0/BLAS/TESTING/CMakeLists.txt;0;")
